decode_env_PKG = \
$(UVMF_VIP_LIBRARY_HOME)/environment_packages/decode_env_pkg/decode_env_pkg.sv

comp_decode_env_pkg:
	$(HVL_COMP_CMD) +incdir+$(UVMF_VIP_LIBRARY_HOME)/environment_packages/decode_env_pkg $(decode_env_PKG)